version: 2
jobs:
  build:
    docker:
      - image: mrgeoffrich/mkdocs-azure-build:latest
      
    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: run mkdocs build
          command: |
            mkdocs build

      - store_artifacts:
          path: site
          destination: site